services:
  db:
    extends:
      file: ./postgres-setup/docker-compose.yaml
      service: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  app:
    build:
      context: ./gutendex
      dockerfile: Dockerfile
    environment:
      - DATABASE_NAME=gutendex
      - DATABASE_USER=gutendex
      - DATABASE_PASSWORD=gutendex_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DEBUG=true
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - SECRET_KEY=your-secret-key-here
      - STATIC_ROOT=/app/staticfiles
      - STATIC_URL=/static/
      - MEDIA_ROOT=/app/media
    volumes:
      # Add this line to map source static files
      - ./gutendex/project/static:/app/static:ro
      # Keep existing volume mappings
      - static_data:/app/staticfiles
      - catalog_data:/app/catalog_files
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               python manage.py updatecatalog &&
               python manage.py runserver 0.0.0.0:8000"
    networks:
      - backend_network
      - frontend_network
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_data:/usr/share/nginx/html/static:ro
    ports:
      - "80:80"
    networks:
      - frontend_network
    depends_on:
      - app

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge

volumes:
  postgres_data:
  static_data:
  catalog_data: