services:
  db:
    extends:
      file: ./postgres-setup/docker-compose.yaml
      service: postgres

  app:
    build:
      context: ./gutendex
      dockerfile: Dockerfile
    container_name: gutendex-app
    environment:
      - DATABASE_NAME=gutendex
      - DATABASE_USER=gutendex
      - DATABASE_PASSWORD=gutendex_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DEBUG=true
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - SECRET_KEY=your-secret-key-here
      - STATIC_ROOT=/app/static
      - MEDIA_ROOT=/app/media
      - UPDATE_CATALOG=true
      - ADMIN_NAMES=admin
      - ADMIN_EMAILS=admin@example.com
      - MANAGER_NAMES=manager
      - MANAGER_EMAILS=manager@example.com
    volumes:
      - static_data:/app/static
      - media_data:/app/media
      - catalog_data:/app/catalog_files
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gutendex_network
    restart: unless-stopped

volumes:
  # Add postgres volume
  postgres_data:
    name: gutendex_postgres_data
  # Application volumes
  static_data:
    name: gutendex_static_data
  media_data:
    name: gutendex_media_data
  catalog_data:
    name: gutendex_catalog_data

networks:
  gutendex_network:
    name: gutendex_network
    driver: bridge
